### ISSUE TITLE
Update Jedi?

### ISSUE THREAD

**Issue by ches** [vheon/JediHTTP#20]
The vendored submodule version is over a year old—is there a reason it's stuck at old version, other than maintainer time to make sure JediHTTP works with a current version?

**Comment by vheon** [comment]
I think the one that JediHTTP vendor is the stable one, isn't that the case?

I was thinking to switch to the dev branch and update it once a month or so actually so this might be the time to start doing it 😕  Do you think is sensible to do it?

**Comment by ches** [comment]
You're right, my mistake, something the author said led me to believe a newer release was considered stable now or that there was an 0.9.x release branch getting updates/fixes (there isn't).

I'm not so clear on why there are `master` and `dev` branches if `master` also does not represent the current stable release, so I wouldn't want to make the decision for you about which moving target to try to track and maintain 😕   It does look like deoplete-jedi [updated their submodule from master recently](https://github.com/zchee/deoplete-jedi/commit/c12f7b214421d0140b7029f3485dd10a93eb2484), FWIW.

**Comment by ches** [comment]
To update, I just clarified with the author—it should have been obvious to check [the `CONTRIBUTING` file](https://github.com/davidhalter/jedi/blob/master/CONTRIBUTING.md) but I had been looking in other places 😇 

> My **master** branch is a 100% stable (should be). I only push to it after I am certain that things are working out. Many people are using Jedi directly from the github master branch.

So if you do want to occasionally sync more recent updates but are concerned about greater maintenance burden of tracking `dev`, it seems like `master` is a compromise.

**Comment by matt-gardner** [comment]
If it helps, I just checked out the `update-to-jedi-master` branch and used it, and it appears to be working.  I spent most of this afternoon trying to get YCM to give me autocompletions using PEP484 type hints, as Jedi [says it will do](https://github.com/davidhalter/jedi/blob/master/docs/docs/features.rst#type-hinting).  I finally found this issue, checked out the code, and it just worked.  No issues noticed so far.

**Comment by vheon** [comment]
@matt-gardner Thanks for trying it out! I had to tweak the Travis configuration since I was getting problem with flake8 on Python 2.6 but it seems to be working now ;) I think that as soon as I get home I will push the update and send a PR updating ycmd/YCM as well :+1:

**Comment by ches** [comment]
Yay, thanks all!
