### ISSUE TITLE
function param type hint support?

### ISSUE THREAD

**Issue by soulomoon** [vheon/JediHTTP#50]
Seems type hint support is not complete(python 3.6):
not with full functionality that jedi can provide, while davidhalter/jedi-vim could do both?
Is there anything I am missing?
```python3
#notworking, but working under jedi.vim
def notworking(n: str) :
    n.*

#working under ycm and jedi.vim
def working():
    v = whatever() # type: str
    n.*
```

**Comment by vheon** [comment]
This project is merely a HTTP wrapper around Jedi, so I'm sorry but your question puzzles me a little 😕  Are you trying to use JediHTTP and you see that an API is missing or you're using something like YCM/ycmd and you don't get the feature you want??

**Comment by soulomoon** [comment]
@vheon I think it should be a Ycm problem, sorry for the trouble here, I should close the issue
